# Tomcat
server:
  port: 90


spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages
    # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
secure:
  ignore:
    urls: #配置白名单路径
      - "/renren-api/api/login" # 登录接口
      - "/renren-api/api/register" # 注册接口
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000